steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hybride-api', '.']

  # Run tests: install dev deps then pytest (blocks deploy on failure)
  - name: 'gcr.io/$PROJECT_ID/hybride-api'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'pip install --no-cache-dir pytest pytest-asyncio && python -m pytest -v --tb=short -o addopts='
    env:
      - 'DB_PASSWORD=fake'
      - 'DB_USER=test'
      - 'DB_NAME=testdb'
      - 'HOME=/tmp'

  # Push image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hybride-api']

  # Deploy to Cloud Run (WEST1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - hybride-api-eu
      - --image=gcr.io/$PROJECT_ID/hybride-api
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --update-env-vars=OWNER_IP=86.212.92.243,2a01:cb05:8700:5900:

images:
  - gcr.io/$PROJECT_ID/hybride-api
