import os
import io
import tempfile
import logging

from config.version import APP_VERSION

logger = logging.getLogger(__name__)


PDF_LABELS = {
    "fr": {
        "title": "Rapport META DONN\u00c9E - 75 Grilles",
        "subtitle": "Analyse HYBRIDE",
        "chance_section": "Projection Num\u00e9ro Chance (1-10) :",
        "chance_line": "N\u00b0{lbl}  -  {val} apparitions",
        "analysis": "Analyse :",
        "no_analysis": "Aucune analyse disponible.",
        "info": "Informations :",
        "window_label": "Fen\u00eatre analys\u00e9e",
        "engine_label": "Moteur",
        "sponsor_title": "Analyse offerte par un Partenaire Officiel",
        "sponsor_contact": "Partenariat & sponsoring :",
        "signature": "Analyse g\u00e9n\u00e9r\u00e9e par HYBRIDE",
        "engine_desc": "Moteur statistique p\u00e9dagogique",
        "generated_by": "G\u00e9n\u00e9r\u00e9 par LotoIA - Module META DONN\u00c9E",
        "disclaimer1": "Analyse statistique p\u00e9dagogique.",
        "disclaimer2": "Aucun r\u00e9sultat n\u2019est garanti.",
        "version": "LotoIA \u2014 Rapport META DONN\u00c9E",
        "ai_note": "Ce rapport est enti\u00e8rement g\u00e9n\u00e9r\u00e9 par intelligence artificielle en collaboration avec le moteur HYBRIDE.",
        "dev_note": "Graphiques et visuels en cours de d\u00e9veloppement.",
        "heatmap_title_balls": "Fr\u00e9quences compl\u00e8tes - Num\u00e9ros (1-49)",
        "heatmap_title_secondary": "Fr\u00e9quences compl\u00e8tes - Num\u00e9ros Chance (1-10)",
        "heatmap_legend_cold": "Froid (rare)",
        "heatmap_legend_hot": "Chaud (fr\u00e9quent)",
    },
    "en": {
        "title": "META DATA Report - 75 Grids",
        "subtitle": "HYBRIDE Analysis",
        "chance_section": "Lucky Number Projection (1-10):",
        "chance_line": "N\u00b0{lbl}  -  {val} occurrences",
        "analysis": "Analysis:",
        "no_analysis": "No analysis available.",
        "info": "Information:",
        "window_label": "Window analysed",
        "engine_label": "Engine",
        "sponsor_title": "Analysis sponsored by an Official Partner",
        "sponsor_contact": "Partnerships & sponsoring:",
        "signature": "Analysis generated by HYBRIDE",
        "engine_desc": "Educational statistical engine",
        "generated_by": "Generated by LotoIA - META DATA Module",
        "disclaimer1": "Educational statistical analysis.",
        "disclaimer2": "No results are guaranteed.",
        "version": "LotoIA \u2014 META DATA Report",
        "ai_note": "This report is entirely generated by artificial intelligence in collaboration with the HYBRIDE engine.",
        "dev_note": "Charts and visuals under development.",
        "heatmap_title_balls": "Complete frequencies - Numbers (1-49)",
        "heatmap_title_secondary": "Complete frequencies - Lucky Numbers (1-10)",
        "heatmap_legend_cold": "Cold (rare)",
        "heatmap_legend_hot": "Hot (frequent)",
    },
    "es": {
        "title": "Informe META DATA - 75 Combinaciones",
        "subtitle": "An\u00e1lisis HYBRIDE",
        "chance_section": "Proyecci\u00f3n N\u00famero de la Suerte (1-10):",
        "chance_line": "N\u00b0{lbl}  -  {val} apariciones",
        "analysis": "An\u00e1lisis:",
        "no_analysis": "Ning\u00fan an\u00e1lisis disponible.",
        "info": "Informaci\u00f3n:",
        "window_label": "Ventana analizada",
        "engine_label": "Motor",
        "sponsor_title": "An\u00e1lisis patrocinado por un Socio Oficial",
        "sponsor_contact": "Colaboraciones y patrocinio:",
        "signature": "An\u00e1lisis generado por HYBRIDE",
        "engine_desc": "Motor estad\u00edstico pedag\u00f3gico",
        "generated_by": "Generado por LotoIA - M\u00f3dulo META DATA",
        "disclaimer1": "An\u00e1lisis estad\u00edstico pedag\u00f3gico.",
        "disclaimer2": "Ning\u00fan resultado est\u00e1 garantizado.",
        "version": "LotoIA \u2014 Informe META DATA",
        "ai_note": "Este informe ha sido generado \u00edntegramente por inteligencia artificial en colaboraci\u00f3n con el motor HYBRIDE.",
        "dev_note": "Gr\u00e1ficos y elementos visuales en desarrollo.",
        "heatmap_title_balls": "Frecuencias completas - N\u00fameros (1-49)",
        "heatmap_title_secondary": "Frecuencias completas - N\u00fameros de la Suerte (1-10)",
        "heatmap_legend_cold": "Fr\u00edo (raro)",
        "heatmap_legend_hot": "Caliente (frecuente)",
    },
    "pt": {
        "title": "Relat\u00f3rio META DATA - 75 Combina\u00e7\u00f5es",
        "subtitle": "An\u00e1lise HYBRIDE",
        "chance_section": "Proje\u00e7\u00e3o N\u00famero da Sorte (1-10):",
        "chance_line": "N\u00b0{lbl}  -  {val} apari\u00e7\u00f5es",
        "analysis": "An\u00e1lise:",
        "no_analysis": "Nenhuma an\u00e1lise dispon\u00edvel.",
        "info": "Informa\u00e7\u00f5es:",
        "window_label": "Janela analisada",
        "engine_label": "Motor",
        "sponsor_title": "An\u00e1lise patrocinada por um Parceiro Oficial",
        "sponsor_contact": "Parcerias e patroc\u00ednio:",
        "signature": "An\u00e1lise gerada por HYBRIDE",
        "engine_desc": "Motor estat\u00edstico pedag\u00f3gico",
        "generated_by": "Gerado por LotoIA - M\u00f3dulo META DATA",
        "disclaimer1": "An\u00e1lise estat\u00edstica pedag\u00f3gica.",
        "disclaimer2": "Nenhum resultado \u00e9 garantido.",
        "version": "LotoIA \u2014 Relat\u00f3rio META DATA",
        "ai_note": "Este relat\u00f3rio foi inteiramente gerado por intelig\u00eancia artificial em colabora\u00e7\u00e3o com o motor HYBRIDE.",
        "dev_note": "Gr\u00e1ficos e elementos visuais em desenvolvimento.",
        "heatmap_title_balls": "Frequ\u00eancias completas - N\u00fameros (1-49)",
        "heatmap_title_secondary": "Frequ\u00eancias completas - N\u00fameros da Sorte (1-10)",
        "heatmap_legend_cold": "Frio (raro)",
        "heatmap_legend_hot": "Quente (frequente)",
    },
    "de": {
        "title": "META-DATEN Bericht - 75 Kombinationen",
        "subtitle": "HYBRIDE-Analyse",
        "chance_section": "Projektion Gl\u00fcckszahl (1-10):",
        "chance_line": "Nr.{lbl}  -  {val} Vorkommen",
        "analysis": "Analyse:",
        "no_analysis": "Keine Analyse verf\u00fcgbar.",
        "info": "Informationen:",
        "window_label": "Analysiertes Fenster",
        "engine_label": "Engine",
        "sponsor_title": "Analyse gesponsert von einem offiziellen Partner",
        "sponsor_contact": "Partnerschaften & Sponsoring:",
        "signature": "Analyse erstellt von HYBRIDE",
        "engine_desc": "P\u00e4dagogische Statistik-Engine",
        "generated_by": "Erstellt von LotoIA - META-DATEN Modul",
        "disclaimer1": "P\u00e4dagogische statistische Analyse.",
        "disclaimer2": "Keine Ergebnisse werden garantiert.",
        "version": "LotoIA \u2014 META-DATEN Bericht",
        "ai_note": "Dieser Bericht wurde vollst\u00e4ndig durch k\u00fcnstliche Intelligenz in Zusammenarbeit mit der HYBRIDE-Engine erstellt.",
        "dev_note": "Diagramme und Grafiken in Entwicklung.",
        "heatmap_title_balls": "Vollst\u00e4ndige H\u00e4ufigkeiten - Nummern (1-49)",
        "heatmap_title_secondary": "Vollst\u00e4ndige H\u00e4ufigkeiten - Gl\u00fcckszahlen (1-10)",
        "heatmap_legend_cold": "Kalt (selten)",
        "heatmap_legend_hot": "Heiss (h\u00e4ufig)",
    },
    "nl": {
        "title": "META DATA Rapport - 75 Combinaties",
        "subtitle": "HYBRIDE-analyse",
        "chance_section": "Projectie Geluksnummer (1-10):",
        "chance_line": "Nr.{lbl}  -  {val} voorkomens",
        "analysis": "Analyse:",
        "no_analysis": "Geen analyse beschikbaar.",
        "info": "Informatie:",
        "window_label": "Geanalyseerd venster",
        "engine_label": "Engine",
        "sponsor_title": "Analyse aangeboden door een Offici\u00eble Partner",
        "sponsor_contact": "Partnerschappen & sponsoring:",
        "signature": "Analyse gegenereerd door HYBRIDE",
        "engine_desc": "Educatieve statistische engine",
        "generated_by": "Gegenereerd door LotoIA - META DATA Module",
        "disclaimer1": "Educatieve statistische analyse.",
        "disclaimer2": "Geen resultaten worden gegarandeerd.",
        "version": "LotoIA \u2014 META DATA Rapport",
        "ai_note": "Dit rapport is volledig gegenereerd door kunstmatige intelligentie in samenwerking met de HYBRIDE-engine.",
        "dev_note": "Grafieken en visualisaties in ontwikkeling.",
        "heatmap_title_balls": "Volledige frequenties - Nummers (1-49)",
        "heatmap_title_secondary": "Volledige frequenties - Geluksnummers (1-10)",
        "heatmap_legend_cold": "Koud (zeldzaam)",
        "heatmap_legend_hot": "Heet (frequent)",
    },
}


def _utf8_clean(text):
    """Nettoie le texte : remplace les caracteres Unicode problematiques par des equivalents ASCII safe pour ReportLab/Vera."""
    if not text:
        return ""
    replacements = {
        "\u2192": "->",   # -> RIGHTWARDS ARROW
        "\u2190": "<-",   # <- LEFTWARDS ARROW
        "\u2194": "<->",  # <-> LEFT RIGHT ARROW
        "\u2013": "-",    # - EN DASH
        "\u2014": "-",    # - EM DASH
        "\u2018": "'",    # ' LEFT SINGLE QUOTATION MARK
        "\u2019": "'",    # ' RIGHT SINGLE QUOTATION MARK
        "\u201C": '"',    # " LEFT DOUBLE QUOTATION MARK
        "\u201D": '"',    # " RIGHT DOUBLE QUOTATION MARK
        "\u2026": "...",  # ... HORIZONTAL ELLIPSIS
        "\u00A0": " ",    # NO-BREAK SPACE
        "\u2022": "-",    # - BULLET
        "\u25A0": "-",    # - BLACK SQUARE
        "\u25A1": "-",    # - WHITE SQUARE
        "\u2023": "-",    # - TRIANGULAR BULLET
        "\u00B7": ".",    # . MIDDLE DOT
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def _register_fonts(pdfmetrics, TTFont):
    """Enregistre polices UTF-8 : DejaVuSans (Linux/Cloud Run) -> Vera (fallback ReportLab)."""
    import reportlab as _rl
    _rl_fonts = os.path.join(os.path.dirname(_rl.__file__), 'fonts')
    _font_map = {
        'DejaVuSans': [
            os.path.join(_rl_fonts, 'DejaVuSans.ttf'),
            '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
            os.path.join(_rl_fonts, 'Vera.ttf'),
        ],
        'DejaVuSans-Bold': [
            os.path.join(_rl_fonts, 'DejaVuSans-Bold.ttf'),
            '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
            os.path.join(_rl_fonts, 'VeraBd.ttf'),
        ],
        'DejaVuSans-Oblique': [
            os.path.join(_rl_fonts, 'DejaVuSans-Oblique.ttf'),
            '/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf',
            os.path.join(_rl_fonts, 'VeraIt.ttf'),
        ],
    }
    for _name, _paths in _font_map.items():
        for _path in _paths:
            if os.path.isfile(_path):
                try:
                    pdfmetrics.registerFont(TTFont(_name, _path))
                    logger.info(f"[META-PDF] Police {_name} -> {os.path.basename(_path)}")
                except Exception as _fe:
                    logger.warning(f"[META-PDF] Echec {_name} avec {_path}: {_fe}")
                    continue
                break
        else:
            logger.error(f"[META-PDF] Aucune police trouvee pour {_name}")


def generate_meta_graph_image(graph_data: dict) -> str:
    """
    Genere une image PNG contenant un bar chart + pie chart cote a cote.
    Retourne le chemin du fichier temporaire PNG.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    labels = graph_data.get("labels", [])
    values = graph_data.get("values", [])

    if not labels or not values or len(labels) != len(values):
        raise ValueError("graph_data invalide : labels et values requis, memes longueurs")

    bar_colors = ['#4285F4', '#34A853', '#FBBC05', '#EA4335', '#A142F4']
    pie_colors = ['#1A73E8', '#188038', '#F9AB00', '#D93025', '#9334E6']

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

    # Bar chart (gauche)
    ax1.bar(labels, values, color=bar_colors[:len(labels)])
    ax1.set_title("Top 5 Fr\u00e9quences", fontsize=13, fontweight='bold')
    ax1.set_xlabel("Num\u00e9ros")
    ax1.set_ylabel("Fr\u00e9quence")
    ax1.grid(axis='y', alpha=0.15)

    # Pie chart (droite)
    pie_labels = [f"N\u00b0{l} ({v})" for l, v in zip(labels, values)]
    ax2.pie(
        values, labels=pie_labels, colors=pie_colors[:len(labels)],
        autopct='%1.0f%%', startangle=90, counterclock=False,
        textprops={'fontsize': 9},
        wedgeprops={'linewidth': 0.5, 'edgecolor': 'white'}
    )
    ax2.set_title("R\u00e9partition Top 5", fontsize=13, fontweight='bold')

    plt.tight_layout()

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    tmp_path = tmp.name
    tmp.close()

    fig.savefig(tmp_path, format="png", dpi=200, facecolor='white', bbox_inches='tight')
    plt.close(fig)

    logger.info(f"[META-PDF] Graph image generee : {tmp_path}")
    return tmp_path


def generate_meta_pdf(analysis: str = "", window: str = "75 tirages",
                      engine: str = "HYBRIDE", graph: str = None,
                      graph_data: dict = None, chance_data: dict = None,
                      sponsor: str = None, lang: str = "fr",
                      all_freq_boules: dict = None,
                      all_freq_secondary: dict = None) -> io.BytesIO:
    """
    Genere le PDF officiel META75 via ReportLab.
    Retourne un BytesIO contenant le PDF.

    Raises:
        ImportError: si reportlab n'est pas installe
        Exception: toute erreur de generation
    """
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    logger.info("[META-PDF] Debut generation PDF")

    # Enregistrer polices UTF-8
    _register_fonts(pdfmetrics, TTFont)

    L = PDF_LABELS.get(lang, PDF_LABELS["fr"])

    buf = io.BytesIO()
    w, h = A4
    c = canvas.Canvas(buf, pagesize=A4)
    margin_bottom = 30 * mm

    y = h - 40 * mm
    logger.info("[META-PDF] Canvas cree OK")

    # Titre
    c.setFont("DejaVuSans-Bold", 22)
    c.drawCentredString(w / 2, y, L["title"])
    y -= 12 * mm

    # Sous-titre
    c.setFont("DejaVuSans-Bold", 16)
    c.drawCentredString(w / 2, y, L["subtitle"])
    y -= 10 * mm

    # Separateur
    c.setStrokeColorRGB(0, 0, 0)
    c.setLineWidth(0.5)
    c.line(15 * mm, y, w - 15 * mm, y)
    y -= 10 * mm

    # --- Validation robuste graph_data ---
    valid_graph = (
        isinstance(graph_data, dict)
        and isinstance(graph_data.get("labels"), list)
        and isinstance(graph_data.get("values"), list)
        and len(graph_data["labels"]) == len(graph_data["values"])
        and len(graph_data["labels"]) > 0
    ) if graph_data else False

    logger.info(f"[META-PDF] graph_data valid: {valid_graph}, "
                f"raw type: {type(graph_data).__name__}, "
                f"graph file: {graph!r}")

    # --- Generation image matplotlib si graph_data valide ---
    generated_graph_path = None
    if valid_graph:
        try:
            generated_graph_path = generate_meta_graph_image(graph_data)
            logger.info(f"[META-PDF] PNG genere OK: {generated_graph_path}")
        except Exception as gen_err:
            logger.warning(f"[META-PDF] Generation graph_data echouee: {gen_err}")

    try:
        # --- Insertion image (graph_data prioritaire, sinon fallback graph path) ---
        effective_graph = generated_graph_path or (graph if graph and os.path.isfile(graph) else "")
        if effective_graph and os.path.isfile(effective_graph):
            try:
                from reportlab.lib.utils import ImageReader
                img = ImageReader(effective_graph)

                # Coordonnees A4 safe (portrait 595x842 points)
                img_x = 60
                img_draw_y = y - 200          # image juste sous separateur
                img_draw_w = 480
                img_draw_h = 190

                c.drawImage(
                    img, img_x, img_draw_y,
                    width=img_draw_w, height=img_draw_h,
                    preserveAspectRatio=True, mask='auto'
                )
                y = img_draw_y - 8 * mm       # pousser Y sous l'image
                logger.info(f"[META-PDF] Image inseree OK a y={img_draw_y}")
            except Exception as img_err:
                logger.warning(f"[META-PDF] Image ignoree: {img_err}")
        else:
            logger.info("[META-PDF] Aucune image a inserer")

        # -- Section Numero Chance (1-10) --
        if chance_data and isinstance(chance_data, dict):
            chance_labels = chance_data.get("labels", [])
            chance_values = chance_data.get("values", [])
            if chance_labels and chance_values:
                # Garde-fou saut de page
                if y < 40 * mm:
                    c.showPage()
                    y = h - 30 * mm

                c.setFont("DejaVuSans-Bold", 13)
                c.drawString(15 * mm, y, L["chance_section"])
                y -= 7 * mm
                c.setFont("DejaVuSans", 11)
                for lbl, val in zip(chance_labels, chance_values):
                    c.drawString(20 * mm, y, L["chance_line"].format(lbl=lbl, val=val))
                    y -= 5.5 * mm
                y -= 4 * mm
                logger.info(f"[META-PDF] Section Numero Chance OK ({len(chance_labels)} entrees)")

        # Bloc analyse
        c.setFont("DejaVuSans-Bold", 13)
        c.drawString(15 * mm, y, L["analysis"])
        y -= 7 * mm

        analysis_text = _utf8_clean(analysis) or L["no_analysis"]
        text_obj = c.beginText(15 * mm, y)
        text_obj.setFont("DejaVuSans", 11)
        text_obj.setLeading(16)
        max_chars = 90
        for raw_line in analysis_text.split('\n'):
            line = raw_line
            while len(line) > max_chars:
                cut = line[:max_chars].rfind(' ')
                if cut <= 0:
                    cut = max_chars
                text_obj.textLine(line[:cut])
                line = line[cut:].lstrip()
            text_obj.textLine(line)
        c.drawText(text_obj)
        y = text_obj.getY() - 8 * mm
        logger.info("[META-PDF] Bloc analyse OK")

        # Saut de page si espace insuffisant
        if y < margin_bottom:
            c.showPage()
            y = h - 30 * mm

        # Bloc infos
        c.setFont("DejaVuSans-Bold", 13)
        c.drawString(15 * mm, y, L["info"])
        y -= 7 * mm

        c.setFont("DejaVuSans", 11)
        window_text = _utf8_clean(window) or "75 tirages"
        engine_text = _utf8_clean(engine) or "HYBRIDE"
        c.drawString(15 * mm, y, f"{L['window_label']} : {window_text}")
        y -= 6 * mm
        c.drawString(15 * mm, y, f"{L['engine_label']} : {engine_text}")
        y -= 10 * mm

        # Bloc sponsor si present
        sponsor_text = _utf8_clean(sponsor)
        if sponsor_text:
            c.setStrokeColorRGB(0.7, 0.7, 0.7)
            c.setLineWidth(0.4)
            c.line(15 * mm, y, w - 15 * mm, y)
            y -= 8 * mm

            c.setFillColorRGB(0.1, 0.1, 0.1)
            c.setFont("DejaVuSans", 10)
            c.drawCentredString(w / 2, y, L["sponsor_title"])
            y -= 6 * mm

            c.setFont("DejaVuSans", 9)
            c.drawCentredString(w / 2, y, L["sponsor_contact"])
            y -= 5 * mm

            email_text = "contact@lotoia.fr"
            email_width = c.stringWidth(email_text, "DejaVuSans", 9)
            email_x1 = (w - email_width) / 2
            email_x2 = email_x1 + email_width
            c.drawCentredString(w / 2, y, email_text)
            c.linkURL("mailto:contact@lotoia.fr", (email_x1, y - 2, email_x2, y + 10), relative=0)
            y -= 10 * mm

        # ============ PAGE 2 — HEATMAP (or footer on page 1) ============
        if all_freq_boules:
            from services.pdf_heatmap import draw_heatmap_grid, draw_legend_bar

            # Convert string keys to int
            freq_b = {int(k): v for k, v in all_freq_boules.items()}
            freq_s = {int(k): v for k, v in all_freq_secondary.items()} if all_freq_secondary else {}

            c.showPage()
            y = h - 55

            # Title boules
            c.setFillColorRGB(0, 0, 0)
            c.setFont("DejaVuSans-Bold", 13)
            c.drawCentredString(w / 2, y, L["heatmap_title_balls"])
            y -= 28

            # Grid boules 7x7 = 49 cells, cell 65x28pt, centred
            grid_w = 7 * 65
            grid_x = (w - grid_w) / 2
            y = draw_heatmap_grid(c, grid_x, y, freq_b, range(1, 50), cols=7, cell_w=65, cell_h=28)
            y -= 20

            # Title chance
            c.setFillColorRGB(0, 0, 0)
            c.setFont("DejaVuSans-Bold", 13)
            c.drawCentredString(w / 2, y, L["heatmap_title_secondary"])
            y -= 28

            # Grid chance 5x2 = 10 cells, cell 65x28pt, centred
            grid_w_s = 5 * 65
            grid_x_s = (w - grid_w_s) / 2
            y = draw_heatmap_grid(c, grid_x_s, y, freq_s, range(1, 11), cols=5, cell_w=65, cell_h=28)
            y -= 25

            # Legend bar
            legend_w = 300
            legend_x = (w - legend_w) / 2
            y = draw_legend_bar(c, legend_x, y, legend_w, 12, L["heatmap_legend_cold"], L["heatmap_legend_hot"])
            y -= 15

            # Separator
            c.setStrokeColorRGB(0, 0, 0)
            c.setLineWidth(0.5)
            c.line(15 * mm, y, w - 15 * mm, y)
            y -= 10 * mm

            # Footer (same as page 1)
            c.setFillColorRGB(0, 0, 0)
            c.setFont("DejaVuSans-Bold", 11)
            c.drawCentredString(w / 2, y, L["signature"])
            y -= 6 * mm
            c.setFont("DejaVuSans", 10)
            c.drawCentredString(w / 2, y, L["engine_desc"])
            y -= 8 * mm
            c.setFont("DejaVuSans-Oblique", 10)
            c.drawCentredString(w / 2, y, L["generated_by"])
            y -= 10 * mm
            c.setFont("DejaVuSans", 9)
            c.drawCentredString(w / 2, y, L["disclaimer1"])
            y -= 5 * mm
            c.drawCentredString(w / 2, y, L["disclaimer2"])
            y -= 10 * mm
            c.setFillColorRGB(150 / 255, 150 / 255, 150 / 255)
            c.setFont("DejaVuSans-Oblique", 8)
            c.drawCentredString(w / 2, y, f"{L['version']} v{APP_VERSION}")

        else:
            # No heatmap data — footer on page 1 (retro-compatibility)
            if y < margin_bottom:
                c.showPage()
                y = h - 30 * mm

            c.setStrokeColorRGB(0, 0, 0)
            c.setLineWidth(0.5)
            c.line(15 * mm, y, w - 15 * mm, y)
            y -= 10 * mm

            c.setFillColorRGB(0, 0, 0)
            c.setFont("DejaVuSans-Bold", 11)
            c.drawCentredString(w / 2, y, L["signature"])
            y -= 6 * mm
            c.setFont("DejaVuSans", 10)
            c.drawCentredString(w / 2, y, L["engine_desc"])
            y -= 8 * mm
            c.setFont("DejaVuSans-Oblique", 10)
            c.drawCentredString(w / 2, y, L["generated_by"])
            y -= 10 * mm
            c.setFont("DejaVuSans", 9)
            c.drawCentredString(w / 2, y, L["disclaimer1"])
            y -= 5 * mm
            c.drawCentredString(w / 2, y, L["disclaimer2"])
            y -= 10 * mm
            c.setFillColorRGB(150 / 255, 150 / 255, 150 / 255)
            c.setFont("DejaVuSans-Oblique", 8)
            c.drawCentredString(w / 2, y, f"{L['version']} v{APP_VERSION}")
            y -= 7 * mm
            c.drawCentredString(w / 2, y, L["ai_note"])
            y -= 7 * mm
            c.drawCentredString(w / 2, y, L["dev_note"])

        c.save()
        buf.seek(0)
        logger.info("[META-PDF] PDF genere OK")

        return buf

    finally:
        # Nettoyage fichier temporaire graph_data
        if generated_graph_path:
            try:
                os.unlink(generated_graph_path)
                logger.info(f"[META-PDF] Fichier temp supprime : {generated_graph_path}")
            except OSError:
                pass
